# Generated by Django 4.2.5 on 2023-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecompressor', '0003_compressedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedimage',
            name='size',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
