# Generated by Django 4.2.5 on 2023-11-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecompressor', '0004_compressedimage_size_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
