# Generated by Django 4.2.5 on 2023-11-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecompressor', '0005_alter_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
